### ISSUE TITLE
implement favorite movie into room database

### ISSUE THREAD

**Issue by aridwiprayogo** [aridwiprayogo/PopularMovie#4]
when the user clicked icon love/like it will be stored in local database(room) and then retrive it into recyclerview

_Sent from my ZenFone Max Pro (M1) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by arsalanfakhar** [comment]
Like movie means can you clarify the problem a bit

**Comment by aridwiprayogo** [comment]
when the user clicked icon love/like it will be stored in local database(room) and then retrive it into recyclerview

**Comment by theapache64** [comment]
@arsalanfakhar Are you working on this issue ?

**Comment by aridwiprayogo** [comment]
@theapache64 I thought they don't 

_Sent from my ZenFone Max Pro (M1) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
